version: '3.2'

services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./www:/var/www/html"
      - "./www/apache:/etc/apache2/sites-available"
    links:
      - database
  database:
    image: mysql:5.7
    ports: 
      - "443:443" 
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_PASSWORD=123
       
       
       
       #docker compose up -d --build
       #docker stop 'id ex' f31a2a675e10